Added letter "g" to Drpepper
codewithnick/ascii-art pull request #1012
Opened 2023-10-29 10:29 UTC by aryantanwarr

*Describes your contribution*

### Referenced Issues

closes #970

2023-10-29 16:14 UTC, AnshumanMahato requested changes

2023-10-29 16:14 UTC, AnshumanMahato commented on Fonts/drpepper/drpepper.h
>          char **g()
<img width="70" alt="image" src="https://github.com/codewithnick/ascii-art/assets/58422570/d443d565-d8ef-46e5-953e-6542ea6340cd">

'g' must go one row below 'A'. Take an extra row and keep the top row empty.

2023-10-30 04:31 UTC, aryantanwarr commented
@AnshumanMahato Updated the required changes to the letter 'g' in Drpepper.

2023-10-30 09:35 UTC, AnshumanMahato approved these changes

2023-10-30 09:35 UTC, merged