bug-fix\clear-matrix
codewithnick/ascii-art pull request #1144
Opened 2024-10-10 05:22 UTC by nakul-py

*After printing a sentence i clear the letters matrix and reset the column pointer to zero .*

*OUTPUT*

![Screenshot from 2024-10-10 10-47-48](https://github.com/user-attachments/assets/2a9d1101-d84a-4c56-8468-933b6e6e87f9)

closes #1129

2024-10-10 05:25 UTC, codewithnick commented
@AnshumanMahato can you please verify this

2024-10-11 10:02 UTC, nakul-py commented
@codewithnick will @AnshumanMahato review this quick?

2024-10-11 10:51 UTC, AnshumanMahato commented
Give me some time... will do this by EOD

2024-10-11 12:53 UTC, AnshumanMahato requested changes

2024-10-11 12:53 UTC, AnshumanMahato commented on Fonts/fonts.h
> +        for(int i = 0; i < def_rows; i++) {
I think everything seems good. Just change this `int i` to `unsigned int i`. We are getting some warnings due to a type mismatch. Also, fix any merge conflicts.

2024-10-11 13:05 UTC, nakul-py commented on Fonts/fonts.h
> +        for(int i = 0; i < def_rows; i++) {
@AnshumanMahato done

2024-10-11 13:44 UTC, AnshumanMahato approved these changes
Cool. Everything looks good. Thanks for contributing ✌️🙂

2024-10-11 13:44 UTC, merged