Added 'F' character in straight.h
codewithnick/ascii-art pull request #301
Opened 2023-10-10 20:03 UTC by Stunner33

Hey, i am new to opensource I have add F character in Straight font. If there is any issue plz Let me know.i am ready to contribute

closes #258

2023-10-10 23:45 UTC, AnshumanMahato commented
@Stunner33, thanks for contributing to our project. Although this issue was assigned to someone else, I am merging your PR. But, for further contributions, please get an issue assigned to yourself before opening a PR. This helps in avoiding confusion. I hope you understand, 😊

2023-10-11 05:56 UTC, Stunner33 commented
@AnshumanMahato I am sorry about that, as i said i am new to open-source so wasn't aware of it...Plz Add hacktoberfest-accepted tag.Thank u🙂

2023-10-11 06:26 UTC, AnshumanMahato commented
No worries @Stunner33, Just make the requested changes and ping me here. I'll check and merge.

2023-10-11 06:29 UTC, Stunner33 commented
@AnshumanMahato Ok.I have made the changes for about issues and sent pr already so plz check it..if there any correction then let me know

2023-10-11 06:36 UTC, AnshumanMahato commented
@Stunner33 did you commit those changes?

2023-10-11 06:48 UTC, Stunner33 commented
> @Stunner33 did you commit those changes?
> 

I did make the changes, can you please check it once from your end?

2023-10-11 09:03 UTC, AnshumanMahato commented
> > @Stunner33 did you commit those changes?
> 
> I did make the changes, can you please check it once from your end?

Well, all I have here is that you added the letter F. There is nothing for the changes that I requested after that. You can see the above messages. I have mentioned some changes that I want here.

2023-10-11 12:50 UTC, Stunner33 commented
> > > @Stunner33 did you commit those changes?
> > 
> > I did make the changes, can you please check it once from your end?
> 
> Well, all I have here is that you added the letter F. There is nothing for the changes that I requested after that. You can see the above messages. I have mentioned some changes that I want here.

Plz can u re-mention the changes as i can't find ur message for changes

2023-10-11 13:17 UTC, AnshumanMahato requested changes

2023-10-11 13:17 UTC, AnshumanMahato commented on Fonts/Straight/straight.h
> +            character [][]=' ';
line no 83

2023-10-12 03:35 UTC, AnshumanMahato approved these changes

2023-10-12 03:35 UTC, merged

2023-10-12 03:37 UTC, AnshumanMahato commented
everything is fine... thanks for contributing @Stunner33. 😊 For further contributions, look for missing characters in any fonts. If there is no existing issue open and assigned for that, open an issue for yourself and I will assign that you.

2023-10-12 06:57 UTC, Stunner33 commented
> everything is fine... thanks for contributing @Stunner33. 😊 For further contributions, look for missing characters in any fonts. If there is no existing issue open and assigned for that, open an issue for yourself and I will assign that you.

Thank u@AnshumanMahato and sorry for trouble caused. I may have disturb u by asking too many questions..My apologies 🙂

2023-10-12 07:49 UTC, AnshumanMahato commented
No worries @Stunner33 . Happy to help. That's what we are here for 😊.