Letter c added to the font boomer
codewithnick/ascii-art pull request #356
Opened 2023-10-14 03:05 UTC by Harry121199

*I have added letter c to the font boomer*

### Referenced Issues

closes #348

2023-10-14 08:28 UTC, AnshumanMahato requested changes

2023-10-14 08:28 UTC, AnshumanMahato commented on Fonts/Boomer/boomer.h
> +    char **c()
Adjust the grid so that c aligns with the bottom.

currently, this is happening
<img width="127" alt="image" src="https://github.com/codewithnick/ascii-art/assets/58422570/c1303f9d-26fe-48b9-92be-296ca829584c">

2023-10-14 09:50 UTC, Harry121199 commented on Fonts/Boomer/boomer.h
> +    char **c()
should it match with the bottom of the A?

2023-10-14 11:57 UTC, AnshumanMahato commented on Fonts/Boomer/boomer.h
> +    char **c()
Yes

2023-10-14 18:04 UTC, Harry121199 commented on Fonts/Boomer/boomer.h
> +    char **c()
Done sir.

2023-10-14 18:57 UTC, Harry121199 commented
done all the required changes

2023-10-15 00:07 UTC, AnshumanMahato commented on Fonts/Boomer/boomer.h
> +    char **c()
great. Everything works fine 🥳

2023-10-15 00:08 UTC, AnshumanMahato approved these changes

2023-10-15 00:08 UTC, merged