Added number 8 to boomer
codewithnick/ascii-art pull request #400
Opened 2023-10-15 12:04 UTC by vishalmishraa

*Describes your contribution*

### Referenced Issues

closes #378

2023-10-15 15:53 UTC, AnshumanMahato requested changes

2023-10-15 15:53 UTC, AnshumanMahato commented on Fonts/Boomer/boomer.h
>              char **character = getCharGrid();
pass grid size(rows,cols) here. it should be the exact number of rows and cols that you used in your character not the default values.

2023-10-15 15:54 UTC, AnshumanMahato commented on Fonts/Boomer/boomer.h
>              char **character = getCharGrid();
@vishalmishraa

2023-10-15 16:31 UTC, vishalmishraa commented on Fonts/Boomer/boomer.h
>              char **character = getCharGrid();
done.  Added rows and col i used.

2023-10-16 03:13 UTC, AnshumanMahato approved these changes

2023-10-16 03:13 UTC, merged