Added digit 6 to boomer
codewithnick/ascii-art pull request #401
Opened 2023-10-15 13:58 UTC by Harry121199

*Describes your contribution*

### Referenced Issues

closes #380

2023-10-15 15:56 UTC, AnshumanMahato requested changes

2023-10-15 15:56 UTC, AnshumanMahato commented on Fonts/Boomer/boomer.h
> +        char **character = getCharGrid(7, 8);
pass the exact number of rows and columns that you used to make the character. Nothing extra nothing less.

2023-10-15 19:18 UTC, Harry121199 commented
Done the required changes and updated the digit 6 to boomer.

2023-10-16 03:15 UTC, AnshumanMahato approved these changes

2023-10-16 03:15 UTC, merged