Added 1 to carlos
codewithnick/ascii-art pull request #403
Opened 2023-10-15 17:24 UTC by chengm405

Character: 1
Font: carlos
closes #387

2023-10-15 23:11 UTC, AnshumanMahato requested changes

2023-10-15 23:11 UTC, AnshumanMahato commented on Fonts/carlos/carlos.h
>              char **character = getCharGrid(ROWS,COLS);
pass grid size(rows,cols) here. it should be the exact number of rows and cols that you used in your character, not the default values.

2023-10-15 23:24 UTC, chengm405 commented
added values for chargrid

2023-10-16 03:18 UTC, AnshumanMahato approved these changes

2023-10-16 03:18 UTC, merged