Added character <a> for <starwar>
codewithnick/ascii-art pull request #418
Opened 2023-10-17 00:13 UTC by s-xiae

Added Character \<a> to font \<starwar>

Lowercase a isn't in the code, so I added the code for it (it's the same as uppercase A)
Even though the ascii art for both A's are the same, the input would be different for both, so this way the computer would read both no problem.

closes #417

2023-10-17 07:17 UTC, AnshumanMahato commented
Grate. That's exactly what had to be done. 🫡

By the way, for further PRs, with for any collaborator to assign the issue to you before you make a PR. This is to ensure that duplicates don't happen. Also, don't close issues by yourself. Just link it to the PR and leave the rest.

Anyways, thanks for contributing. 😊

2023-10-17 07:19 UTC, AnshumanMahato requested changes

2023-10-17 07:19 UTC, AnshumanMahato commented on Fonts/starwar/starwar.h
> +        char **character = getCharGrid(ROWS,COLS);
pass the exact no. of rows and columns that you used to make your character.

2023-10-17 07:19 UTC, AnshumanMahato commented on Fonts/starwar/starwar.h
> +        char **character = getCharGrid(ROWS,COLS);
same here as well

2023-10-17 17:09 UTC, s-xiae commented on Fonts/starwar/starwar.h
> +        char **character = getCharGrid(ROWS,COLS);
added the values

2023-10-17 17:09 UTC, s-xiae commented on Fonts/starwar/starwar.h
> +        char **character = getCharGrid(ROWS,COLS);
added the values here too.

2023-10-18 09:19 UTC, AnshumanMahato approved these changes

2023-10-18 09:20 UTC, merged