Number 6 added to starwar
codewithnick/ascii-art pull request #428
Opened 2023-10-17 12:30 UTC by NeerajSh-16

*Describes your contribution*

### Referenced Issues

closes #398

2023-10-17 23:44 UTC, AnshumanMahato requested changes

2023-10-17 23:44 UTC, AnshumanMahato commented on Fonts/starwar/starwar.h
> +            char **character = getCharGrid();
pass the exact no. of rows and columns that you used.

2023-10-17 23:53 UTC, NeerajSh-16 commented on Fonts/starwar/starwar.h
> +            char **character = getCharGrid();
Done Sir.

2023-10-18 09:25 UTC, AnshumanMahato approved these changes

2023-10-18 09:26 UTC, merged