added 4 in straight
codewithnick/ascii-art pull request #450
Opened 2023-10-18 10:47 UTC by Shivansh-243

*Describes your contribution*

### Referenced Issues

closes #446

2023-10-18 23:00 UTC, AnshumanMahato requested changes
adjust the grid so that it aligns with the rest of the characters.

<img width="113" alt="image" src="https://github.com/codewithnick/ascii-art/assets/58422570/8498c718-6ec1-4963-93c3-040ce2196fd0">

I guess it should be resolved by adding an empty row at the top.

2023-10-19 00:31 UTC, Shivansh-243 commented
@AnshumanMahato  if any other changes required please ask

2023-10-19 02:54 UTC, AnshumanMahato approved these changes

2023-10-19 02:54 UTC, AnshumanMahato commented
all good

2023-10-19 02:54 UTC, merged