added 1 in boomer
codewithnick/ascii-art pull request #560
Opened 2023-10-21 10:03 UTC by rishavr920

i added number 1 in boomer merge it plzz

2023-10-21 10:04 UTC, rishavr920 commented
#560

2023-10-21 11:04 UTC, AnshumanMahato requested changes

2023-10-21 11:04 UTC, AnshumanMahato commented on Fonts/Boomer/boomer.h
> +            character[0][0]=character[1][0]=character[2][0]=character[3][0]=character[4][0]=  character[5][0]=  character[6][0]=  character[7][0]=' ';
<img width="421" alt="image" src="https://github.com/codewithnick/ascii-art/assets/58422570/5c2e5117-aaf4-42fc-aa90-b99a17d0d17e">

error upon compilation... please resolve

You have taken a grid of 6 rows and 7 columns but you using 8 rows from what I can see. Please test your code before pushing changes.

2023-10-23 07:35 UTC, rishavr920 commented on Fonts/Boomer/boomer.h
> +            character[0][0]=character[1][0]=character[2][0]=character[3][0]=character[4][0]=  character[5][0]=  character[6][0]=  character[7][0]=' ';
sir I have changed the grid size please check if it alright merge it.

2023-10-23 07:36 UTC, rishavr920 commented
sir I have changed the grid size please check if it alright merge it.

2023-10-23 09:58 UTC, AnshumanMahato commented
hey... did you test your code? It is giving this
![image](https://github.com/codewithnick/ascii-art/assets/58422570/61c78289-7b27-4509-b494-97c32832eeb0)

What's expected is this 
![image](https://github.com/codewithnick/ascii-art/assets/58422570/f801adc4-6aac-41e6-8176-bf2dff26c2ab)

If you are getting stuck somewhere, feel free to ask for help 😊

2023-10-24 08:25 UTC, closed without merging