Added q to boomer Font
codewithnick/ascii-art pull request #563
Opened 2023-10-21 12:17 UTC by IshitaPathak

*Describes your contribution*
Added q to Boomer Font

### Referenced Issues
 
closes #559
closes #593

2023-10-21 23:29 UTC, AnshumanMahato requested changes

2023-10-21 23:29 UTC, AnshumanMahato commented on Fonts/Boomer/boomer.h
> +        char **character = getCharGrid(6, 7);
code is fine. There is just a small issue of alignment. As you know, characters like g,q,p, and y extend below the regular. That is not happening here.
<img width="241" alt="image" src="https://github.com/codewithnick/ascii-art/assets/58422570/7b8737d5-daa4-4b6d-9f33-0ebad6e86526">

Just adjust the grid for this. Taking 3 extra rows and leaving the top 3 rows empty should do the trick

2023-10-22 05:41 UTC, IshitaPathak commented on Fonts/Boomer/boomer.h
> +        char **character = getCharGrid(6, 7);
Yes, I think now alignment issue is resolved
<img width="297" alt="image" src="https://github.com/codewithnick/ascii-art/assets/75848598/fe972118-3181-43ea-81eb-49286fcac14e">
The same issue is with p

2023-10-22 11:39 UTC, AnshumanMahato commented
@IshitaPathak everything works fine here. Thanks for the contribution and the bug hunt. 😁

2023-10-22 11:41 UTC, AnshumanMahato approved these changes

2023-10-22 11:41 UTC, merged