straight z
codewithnick/ascii-art pull request #576
Opened 2023-10-21 16:43 UTC by gourshabrg

*Describes your contribution*

### 

closes ##262

2023-10-21 23:51 UTC, AnshumanMahato requested changes

2023-10-21 23:51 UTC, AnshumanMahato commented on Fonts/Straight/straight.h
> +            char **character = getCharGrid();
Pass the number of rows and columns that you used

2023-10-21 23:51 UTC, AnshumanMahato commented on Fonts/Straight/straight.h
> +            character[1][1] ='_';
Adjust the grid so the z aligns with the rest of the characters. Currently, this is happening.
<img width="84" alt="image" src="https://github.com/codewithnick/ascii-art/assets/58422570/3a51899e-5394-43a0-9b2e-f8885b699c84">

Keeping the top row empty should do the trick.

2023-10-22 07:00 UTC, gourshabrg commented on Fonts/Straight/straight.h
> +            character[1][1] ='_';
how to solve this issue

2023-10-22 15:26 UTC, closed without merging

2023-10-22 15:29 UTC, AnshumanMahato commented
@gourshabrg sorry I missed this one and forgot to reply. Just busy with the festival...

Look what you do... take an extra row for the character and keep the top row empty.. fill ypur character starting from the second row. This should work.