character <d> added to font <Banner>
codewithnick/ascii-art pull request #615
Opened 2023-10-22 12:43 UTC by PANDACR

*character <d> added to font <Banner>*

### Referenced Issues

closes #610

2023-10-22 16:28 UTC, AnshumanMahato requested changes

2023-10-22 16:28 UTC, AnshumanMahato commented on Fonts/banner/banner.h
> +            char **character = getCharGrid(8,3);
d not printing correctly.
currently, this is happening
<img width="115" alt="image" src="https://github.com/codewithnick/ascii-art/assets/58422570/1960d75a-8110-411e-a12e-79c3cf60fbcf">

2023-10-22 17:58 UTC, RITIK-DEVOLOPER commented
updated

2023-10-23 03:59 UTC, AnshumanMahato approved these changes

2023-10-23 03:59 UTC, merged